version: '{branch}.{build}'
branches:
  only:
  - master
  - appveyor
  - ci

image:
- Visual Studio 2017

environment:
  matrix:
  - platform: x86
    VCPKG_DEFAULT_TRIPLET: x86-windows
  - platform: x64
    VCPKG_DEFAULT_TRIPLET: x64-windows

install:
- cmd: cinst wget
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
- vcpkg install json-c
- vcpkg install libyaml
- vcpkg install getopt
- vcpkg install dirent

build_script:
# libmustache
- cmd: >-
    cd C:\projects\libmustache
    
    git submodule update --init
    
    mkdir build
    
    cd build
    
    cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=..\artifacts -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    
    nmake
    
    nmake install

test_script:
- cmd: nmake test

artifacts:
  - path: artifacts
    name: master
    type: zip
