
language: cpp

compiler: gcc

dist: focal

matrix:
  include:
    - dist: xenial
      compiler: gcc
    - dist: xenial
      compiler: clang
    - dist: bionic
      compiler: gcc
    - dist: bionic
      compiler: clang
    - dist: focal
      compiler: gcc
    - dist: focal
      compiler: clang

branches:
  only:
    - master
    - travis
    - ci

before_install: git submodule update --init --recursive && autoreconf -fiv
