language: cpp

compiler:
  - gcc

dist: trusty

sudo: required

branches:
  only:
    - master
    - travis

before_install:
  - git submodule update --init --recursive

install:
  - autoreconf -fiv
  - ./configure --prefix=$HOME/build

script:
  - make all test install
