cmake_minimum_required(VERSION 3.18)

foreach(MUSTACHE_REQUIRED_VARIABLE IN ITEMS
        MUSTACHE_TEST_SOURCE_DIR
        MUSTACHE_TEST_BINARY_ROOT
        MUSTACHE_TEST_GENERATOR
        MUSTACHE_TEST_CXX_COMPILER)
    if(NOT DEFINED ${MUSTACHE_REQUIRED_VARIABLE} OR
            "${${MUSTACHE_REQUIRED_VARIABLE}}" STREQUAL "")
        message(FATAL_ERROR "${MUSTACHE_REQUIRED_VARIABLE} is required")
    endif()
endforeach()

file(READ "${MUSTACHE_TEST_SOURCE_DIR}/vendor/cista/cista.h"
    MUSTACHE_BASELINE_CISTA_HEADER_CONTENTS)
set(MUSTACHE_CISTA_BASE_HASH
    "constexpr auto const BASE_HASH = 0ULL;")
set(MUSTACHE_DOMAIN_CISTA_BASE_HASH
    "constexpr auto const BASE_HASH = 0x9E3779B97F4A7C15ULL;")
string(REPLACE
    "${MUSTACHE_CISTA_BASE_HASH}"
    "${MUSTACHE_DOMAIN_CISTA_BASE_HASH}"
    MUSTACHE_DOMAIN_CISTA_HEADER_CONTENTS
    "${MUSTACHE_BASELINE_CISTA_HEADER_CONTENTS}")
if(MUSTACHE_DOMAIN_CISTA_HEADER_CONTENTS STREQUAL
        MUSTACHE_BASELINE_CISTA_HEADER_CONTENTS)
    message(FATAL_ERROR
        "The controlled Cista base-hash mutation did not match the vendored header")
endif()

set(MUSTACHE_CISTA_VECTOR_MARKER
    "h = hash_combine(h, hash(\"vector\"));")
set(MUSTACHE_DRIFT_CISTA_VECTOR_MARKER
    "h = hash_combine(h, hash(\"vector-algorithm-drift\"));")
string(REPLACE
    "${MUSTACHE_CISTA_VECTOR_MARKER}"
    "${MUSTACHE_DRIFT_CISTA_VECTOR_MARKER}"
    MUSTACHE_DRIFT_CISTA_HEADER_CONTENTS
    "${MUSTACHE_BASELINE_CISTA_HEADER_CONTENTS}")
if(MUSTACHE_DRIFT_CISTA_HEADER_CONTENTS STREQUAL
        MUSTACHE_BASELINE_CISTA_HEADER_CONTENTS)
    message(FATAL_ERROR
        "The controlled Cista recursive-algorithm mutation did not match the vendored header")
endif()

function(mustache_write_cista_package MUSTACHE_PACKAGE_ROOT
        MUSTACHE_HEADER_CONTENTS_VARIABLE)
    set(MUSTACHE_PACKAGE_INCLUDE_DIR
        "${MUSTACHE_PACKAGE_ROOT}/include")
    set(MUSTACHE_PACKAGE_CONFIG_DIR
        "${MUSTACHE_PACKAGE_ROOT}/lib/cmake/cista")
    file(MAKE_DIRECTORY
        "${MUSTACHE_PACKAGE_INCLUDE_DIR}/cista"
        "${MUSTACHE_PACKAGE_CONFIG_DIR}")
    file(WRITE "${MUSTACHE_PACKAGE_INCLUDE_DIR}/cista/serialization.h"
        "${${MUSTACHE_HEADER_CONTENTS_VARIABLE}}")
    file(WRITE "${MUSTACHE_PACKAGE_CONFIG_DIR}/cistaConfig.cmake" [=[
if(NOT TARGET cista::cista)
    add_library(cista::cista INTERFACE IMPORTED)
    get_filename_component(CISTA_TEST_PREFIX
        "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
    set_target_properties(cista::cista PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${CISTA_TEST_PREFIX}/include")
endif()
]=])
endfunction()

set(MUSTACHE_BASELINE_CISTA_ROOT
    "${MUSTACHE_TEST_BINARY_ROOT}/baseline-system-cista")
set(MUSTACHE_DOMAIN_CISTA_ROOT
    "${MUSTACHE_TEST_BINARY_ROOT}/domain-system-cista")
set(MUSTACHE_DRIFT_CISTA_ROOT
    "${MUSTACHE_TEST_BINARY_ROOT}/drift-system-cista")
mustache_write_cista_package("${MUSTACHE_BASELINE_CISTA_ROOT}"
    MUSTACHE_BASELINE_CISTA_HEADER_CONTENTS)
mustache_write_cista_package("${MUSTACHE_DOMAIN_CISTA_ROOT}"
    MUSTACHE_DOMAIN_CISTA_HEADER_CONTENTS)
mustache_write_cista_package("${MUSTACHE_DRIFT_CISTA_ROOT}"
    MUSTACHE_DRIFT_CISTA_HEADER_CONTENTS)

set(MUSTACHE_GENERATOR_ARGUMENTS -G "${MUSTACHE_TEST_GENERATOR}")
if(DEFINED MUSTACHE_TEST_GENERATOR_PLATFORM AND
        NOT MUSTACHE_TEST_GENERATOR_PLATFORM STREQUAL "")
    list(APPEND MUSTACHE_GENERATOR_ARGUMENTS
        -A "${MUSTACHE_TEST_GENERATOR_PLATFORM}")
endif()
if(DEFINED MUSTACHE_TEST_GENERATOR_TOOLSET AND
        NOT MUSTACHE_TEST_GENERATOR_TOOLSET STREQUAL "")
    list(APPEND MUSTACHE_GENERATOR_ARGUMENTS
        -T "${MUSTACHE_TEST_GENERATOR_TOOLSET}")
endif()

set(MUSTACHE_BUILD_CONFIG_ARGUMENTS)
if(DEFINED MUSTACHE_TEST_CONFIG AND
        NOT MUSTACHE_TEST_CONFIG STREQUAL "")
    list(APPEND MUSTACHE_BUILD_CONFIG_ARGUMENTS
        --config "${MUSTACHE_TEST_CONFIG}")
endif()

set(MUSTACHE_FORWARDED_CMAKE_ARGUMENTS)
set(MUSTACHE_EFFECTIVE_TEST_CXX_FLAGS
    "${MUSTACHE_TEST_CXX_FLAGS} -DMUSTACHE_CISTA_MUTATION_CONFIGURATION_SENTINEL=1")
string(STRIP "${MUSTACHE_EFFECTIVE_TEST_CXX_FLAGS}"
    MUSTACHE_EFFECTIVE_TEST_CXX_FLAGS)
macro(mustache_forward_cache_variable MUSTACHE_PARENT_VARIABLE
        MUSTACHE_NESTED_VARIABLE)
    if(DEFINED ${MUSTACHE_PARENT_VARIABLE})
        string(REPLACE ";" "\\;" MUSTACHE_FORWARDED_VALUE
            "${${MUSTACHE_PARENT_VARIABLE}}")
        list(APPEND MUSTACHE_FORWARDED_CMAKE_ARGUMENTS
            "-D${MUSTACHE_NESTED_VARIABLE}=${MUSTACHE_FORWARDED_VALUE}")
    endif()
endmacro()
mustache_forward_cache_variable(MUSTACHE_TEST_CXX_COMPILER_ARG1
    CMAKE_CXX_COMPILER_ARG1)
mustache_forward_cache_variable(MUSTACHE_TEST_CXX_COMPILER_TARGET
    CMAKE_CXX_COMPILER_TARGET)
mustache_forward_cache_variable(MUSTACHE_TEST_CXX_COMPILER_EXTERNAL_TOOLCHAIN
    CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN)
mustache_forward_cache_variable(MUSTACHE_TEST_TOOLCHAIN_FILE
    CMAKE_TOOLCHAIN_FILE)
mustache_forward_cache_variable(MUSTACHE_TEST_SYSROOT CMAKE_SYSROOT)
mustache_forward_cache_variable(MUSTACHE_TEST_OSX_ARCHITECTURES
    CMAKE_OSX_ARCHITECTURES)
mustache_forward_cache_variable(MUSTACHE_TEST_OSX_DEPLOYMENT_TARGET
    CMAKE_OSX_DEPLOYMENT_TARGET)
mustache_forward_cache_variable(MUSTACHE_TEST_MSVC_RUNTIME_LIBRARY
    CMAKE_MSVC_RUNTIME_LIBRARY)
mustache_forward_cache_variable(MUSTACHE_TEST_GENERATOR_INSTANCE
    CMAKE_GENERATOR_INSTANCE)
mustache_forward_cache_variable(MUSTACHE_TEST_BUILD_TYPE CMAKE_BUILD_TYPE)
mustache_forward_cache_variable(MUSTACHE_EFFECTIVE_TEST_CXX_FLAGS
    CMAKE_CXX_FLAGS)
mustache_forward_cache_variable(MUSTACHE_TEST_CXX_FLAGS_DEBUG
    CMAKE_CXX_FLAGS_DEBUG)
mustache_forward_cache_variable(MUSTACHE_TEST_CXX_FLAGS_RELEASE
    CMAKE_CXX_FLAGS_RELEASE)
mustache_forward_cache_variable(MUSTACHE_TEST_CXX_FLAGS_RELWITHDEBINFO
    CMAKE_CXX_FLAGS_RELWITHDEBINFO)
mustache_forward_cache_variable(MUSTACHE_TEST_CXX_FLAGS_MINSIZEREL
    CMAKE_CXX_FLAGS_MINSIZEREL)
mustache_forward_cache_variable(MUSTACHE_TEST_EXE_LINKER_FLAGS
    CMAKE_EXE_LINKER_FLAGS)
mustache_forward_cache_variable(MUSTACHE_TEST_EXE_LINKER_FLAGS_DEBUG
    CMAKE_EXE_LINKER_FLAGS_DEBUG)
mustache_forward_cache_variable(MUSTACHE_TEST_EXE_LINKER_FLAGS_RELEASE
    CMAKE_EXE_LINKER_FLAGS_RELEASE)
mustache_forward_cache_variable(MUSTACHE_TEST_EXE_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO)
mustache_forward_cache_variable(MUSTACHE_TEST_EXE_LINKER_FLAGS_MINSIZEREL
    CMAKE_EXE_LINKER_FLAGS_MINSIZEREL)

function(mustache_configure_and_build_probe MUSTACHE_NAME
        MUSTACHE_CISTA_ROOT MUSTACHE_OUTPUT_EXECUTABLE_VARIABLE)
    set(MUSTACHE_BUILD_DIR
        "${MUSTACHE_TEST_BINARY_ROOT}/${MUSTACHE_NAME}-build")
    set(MUSTACHE_RUNTIME_DIR
        "${MUSTACHE_TEST_BINARY_ROOT}/${MUSTACHE_NAME}-bin")
    execute_process(
        COMMAND "${CMAKE_COMMAND}"
            -S "${MUSTACHE_TEST_SOURCE_DIR}"
            -B "${MUSTACHE_BUILD_DIR}"
            ${MUSTACHE_GENERATOR_ARGUMENTS}
            "-DCMAKE_CXX_COMPILER=${MUSTACHE_TEST_CXX_COMPILER}"
            ${MUSTACHE_FORWARDED_CMAKE_ARGUMENTS}
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${MUSTACHE_RUNTIME_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=${MUSTACHE_RUNTIME_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=${MUSTACHE_RUNTIME_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO=${MUSTACHE_RUNTIME_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL=${MUSTACHE_RUNTIME_DIR}"
            -DMUSTACHE_BUILD_CLI=OFF
            -DMUSTACHE_ENABLE_TESTS=ON
            -DMUSTACHE_ENABLE_HARDENING=OFF
            -DMUSTACHE_ENABLE_JSON=OFF
            -DMUSTACHE_ENABLE_YAML=OFF
            -DMUSTACHE_ENABLE_ARCHIVED_TEMPLATES=ON
            -DMUSTACHE_USE_SYSTEM_CISTA=ON
            -DMUSTACHE_USE_SYSTEM_XXHASH=OFF
            -DMUSTACHE_WARNINGS_AS_ERRORS=ON
            -DMUSTACHE_TEST_CISTA_VERSION_MUTATION=ON
            "-Dcista_DIR=${MUSTACHE_CISTA_ROOT}/lib/cmake/cista"
        RESULT_VARIABLE MUSTACHE_CONFIGURE_RESULT
        OUTPUT_VARIABLE MUSTACHE_CONFIGURE_OUTPUT
        ERROR_VARIABLE MUSTACHE_CONFIGURE_ERROR)
    if(NOT MUSTACHE_CONFIGURE_RESULT EQUAL 0)
        message(FATAL_ERROR
            "Configuring the ${MUSTACHE_NAME} Cista mutation probe failed:\n${MUSTACHE_CONFIGURE_OUTPUT}${MUSTACHE_CONFIGURE_ERROR}")
    endif()
    file(STRINGS "${MUSTACHE_BUILD_DIR}/CMakeCache.txt"
        MUSTACHE_NESTED_CXX_FLAGS_LINE
        REGEX "^CMAKE_CXX_FLAGS:STRING=")
    if(NOT MUSTACHE_NESTED_CXX_FLAGS_LINE STREQUAL
            "CMAKE_CXX_FLAGS:STRING=${MUSTACHE_EFFECTIVE_TEST_CXX_FLAGS}")
        message(FATAL_ERROR
            "The ${MUSTACHE_NAME} Cista mutation probe did not inherit the parent compiler ABI flags")
    endif()

    execute_process(
        COMMAND "${CMAKE_COMMAND}" --build "${MUSTACHE_BUILD_DIR}"
            --target test_cista_version_mutation
            ${MUSTACHE_BUILD_CONFIG_ARGUMENTS}
        RESULT_VARIABLE MUSTACHE_BUILD_RESULT
        OUTPUT_VARIABLE MUSTACHE_BUILD_OUTPUT
        ERROR_VARIABLE MUSTACHE_BUILD_ERROR)
    if(NOT MUSTACHE_BUILD_RESULT EQUAL 0)
        message(FATAL_ERROR
            "Building the ${MUSTACHE_NAME} Cista mutation probe failed:\n${MUSTACHE_BUILD_OUTPUT}${MUSTACHE_BUILD_ERROR}")
    endif()

    set(${MUSTACHE_OUTPUT_EXECUTABLE_VARIABLE}
        "${MUSTACHE_RUNTIME_DIR}/test_cista_version_mutation${MUSTACHE_TEST_EXECUTABLE_SUFFIX}"
        PARENT_SCOPE)
endfunction()

function(mustache_expect_algorithm_drift_rejection MUSTACHE_CISTA_ROOT)
    set(MUSTACHE_BUILD_DIR
        "${MUSTACHE_TEST_BINARY_ROOT}/drift-build")
    execute_process(
        COMMAND "${CMAKE_COMMAND}"
            -S "${MUSTACHE_TEST_SOURCE_DIR}"
            -B "${MUSTACHE_BUILD_DIR}"
            ${MUSTACHE_GENERATOR_ARGUMENTS}
            "-DCMAKE_CXX_COMPILER=${MUSTACHE_TEST_CXX_COMPILER}"
            ${MUSTACHE_FORWARDED_CMAKE_ARGUMENTS}
            -DMUSTACHE_BUILD_CLI=OFF
            -DMUSTACHE_ENABLE_TESTS=OFF
            -DMUSTACHE_ENABLE_HARDENING=OFF
            -DMUSTACHE_ENABLE_JSON=OFF
            -DMUSTACHE_ENABLE_YAML=OFF
            -DMUSTACHE_ENABLE_ARCHIVED_TEMPLATES=ON
            -DMUSTACHE_USE_SYSTEM_CISTA=ON
            -DMUSTACHE_USE_SYSTEM_XXHASH=OFF
            -DMUSTACHE_WARNINGS_AS_ERRORS=ON
            "-Dcista_DIR=${MUSTACHE_CISTA_ROOT}/lib/cmake/cista"
        RESULT_VARIABLE MUSTACHE_CONFIGURE_RESULT
        OUTPUT_VARIABLE MUSTACHE_CONFIGURE_OUTPUT
        ERROR_VARIABLE MUSTACHE_CONFIGURE_ERROR)
    if(MUSTACHE_CONFIGURE_RESULT EQUAL 0)
        message(FATAL_ERROR
            "Cista recursive type-version algorithm drift was not rejected during configuration")
    endif()
    set(MUSTACHE_CONFIGURE_LOG
        "${MUSTACHE_CONFIGURE_OUTPUT}${MUSTACHE_CONFIGURE_ERROR}")
    string(FIND "${MUSTACHE_CONFIGURE_LOG}"
        "The selected Cista runtime type-version algorithm"
        MUSTACHE_EXPECTED_REJECTION_POSITION)
    if(MUSTACHE_EXPECTED_REJECTION_POSITION EQUAL -1)
        message(FATAL_ERROR
            "Cista recursive type-version algorithm drift failed at the wrong boundary:\n${MUSTACHE_CONFIGURE_LOG}")
    endif()
endfunction()

mustache_configure_and_build_probe(baseline
    "${MUSTACHE_BASELINE_CISTA_ROOT}" MUSTACHE_BASELINE_PROBE)
mustache_configure_and_build_probe(domain
    "${MUSTACHE_DOMAIN_CISTA_ROOT}" MUSTACHE_DOMAIN_PROBE)
mustache_expect_algorithm_drift_rejection(
    "${MUSTACHE_DRIFT_CISTA_ROOT}")

set(MUSTACHE_BASELINE_ARCHIVE
    "${MUSTACHE_TEST_BINARY_ROOT}/baseline.archive")
set(MUSTACHE_BASELINE_TAG
    "${MUSTACHE_TEST_BINARY_ROOT}/baseline.tag")
set(MUSTACHE_DOMAIN_ARCHIVE
    "${MUSTACHE_TEST_BINARY_ROOT}/domain.archive")
set(MUSTACHE_DOMAIN_TAG
    "${MUSTACHE_TEST_BINARY_ROOT}/domain.tag")

function(mustache_run_probe MUSTACHE_DESCRIPTION MUSTACHE_EXECUTABLE)
    execute_process(
        COMMAND "${MUSTACHE_EXECUTABLE}" ${ARGN}
        RESULT_VARIABLE MUSTACHE_PROBE_RESULT
        OUTPUT_VARIABLE MUSTACHE_PROBE_OUTPUT
        ERROR_VARIABLE MUSTACHE_PROBE_ERROR)
    if(NOT MUSTACHE_PROBE_RESULT EQUAL 0)
        message(FATAL_ERROR
            "${MUSTACHE_DESCRIPTION} failed:\n${MUSTACHE_PROBE_OUTPUT}${MUSTACHE_PROBE_ERROR}")
    endif()
endfunction()

mustache_run_probe("Producing the native baseline archive"
    "${MUSTACHE_BASELINE_PROBE}" produce
    "${MUSTACHE_BASELINE_ARCHIVE}" "${MUSTACHE_BASELINE_TAG}")
mustache_run_probe("Rejecting the native baseline from the alternate domain"
    "${MUSTACHE_DOMAIN_PROBE}" reject
    "${MUSTACHE_BASELINE_ARCHIVE}" "${MUSTACHE_BASELINE_TAG}")
mustache_run_probe("Producing the alternate native domain archive"
    "${MUSTACHE_DOMAIN_PROBE}" produce
    "${MUSTACHE_DOMAIN_ARCHIVE}" "${MUSTACHE_DOMAIN_TAG}")
mustache_run_probe("Rejecting the alternate native domain from the baseline build"
    "${MUSTACHE_BASELINE_PROBE}" reject
    "${MUSTACHE_DOMAIN_ARCHIVE}" "${MUSTACHE_DOMAIN_TAG}")
