if(NOT DEFINED MUSTACHE_LIBRARY OR NOT EXISTS "${MUSTACHE_LIBRARY}")
    message(FATAL_ERROR "MUSTACHE_LIBRARY must name the built shared library")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/archive_runtime_dependency_helpers.cmake")

file(GET_RUNTIME_DEPENDENCIES
    LIBRARIES "${MUSTACHE_LIBRARY}"
    RESOLVED_DEPENDENCIES_VAR MUSTACHE_RESOLVED_DEPENDENCIES
    UNRESOLVED_DEPENDENCIES_VAR MUSTACHE_UNRESOLVED_DEPENDENCIES)

set(MUSTACHE_ALL_DEPENDENCIES
    ${MUSTACHE_RESOLVED_DEPENDENCIES}
    ${MUSTACHE_UNRESOLVED_DEPENDENCIES})
foreach(MUSTACHE_DEPENDENCY IN LISTS MUSTACHE_ALL_DEPENDENCIES)
    mustache_is_zlib_runtime_dependency(
        "${MUSTACHE_DEPENDENCY}" MUSTACHE_IS_ZLIB)
    if(MUSTACHE_IS_ZLIB)
        message(FATAL_ERROR
            "production archive support unexpectedly depends on zlib: ${MUSTACHE_DEPENDENCY}")
    endif()
endforeach()
