function(mustache_select_unix_export_format result system_name is_apple is_unix)
    if(NOT is_unix)
        set(format "")
    elseif(is_apple)
        set(format MACHO)
    elseif(system_name STREQUAL "Linux")
        set(format ELF)
    else()
        set(format "")
    endif()
    set(${result} "${format}" PARENT_SCOPE)
endfunction()
