foreach(MUSTACHE_REQUIRED_VARIABLE IN ITEMS
        FUZZ_EXECUTABLE
        FUZZ_DICTIONARY
        FUZZ_RUNNER
        FUZZ_SAFETY_ROOT)
    if(NOT DEFINED ${MUSTACHE_REQUIRED_VARIABLE} OR "${${MUSTACHE_REQUIRED_VARIABLE}}" STREQUAL "")
        message(FATAL_ERROR "${MUSTACHE_REQUIRED_VARIABLE} is required")
    endif()
endforeach()

file(REMOVE_RECURSE "${FUZZ_SAFETY_ROOT}")
set(FUZZ_ALLOWED_SCRATCH_PARENT "${FUZZ_SAFETY_ROOT}")
set(FUZZ_SCRATCH_ROOT "${FUZZ_ALLOWED_SCRATCH_PARENT}/danger")
set(FUZZ_SEED_CORPUS "${FUZZ_SCRATCH_ROOT}/seeds")
set(FUZZ_ARTIFACT_DIRECTORY "${FUZZ_SAFETY_ROOT}/artifacts")
set(FUZZ_SEED_MARKER "${FUZZ_SEED_CORPUS}/marker")
file(MAKE_DIRECTORY "${FUZZ_SEED_CORPUS}" "${FUZZ_ARTIFACT_DIRECTORY}")
file(WRITE "${FUZZ_SEED_MARKER}" "protected seed")

execute_process(
    COMMAND "${CMAKE_COMMAND}"
        "-DFUZZ_EXECUTABLE=${FUZZ_EXECUTABLE}"
        "-DFUZZ_DICTIONARY=${FUZZ_DICTIONARY}"
        "-DFUZZ_SEED_CORPUS=${FUZZ_SEED_CORPUS}"
        "-DFUZZ_ALLOWED_SCRATCH_PARENT=${FUZZ_ALLOWED_SCRATCH_PARENT}"
        "-DFUZZ_SCRATCH_ROOT=${FUZZ_SCRATCH_ROOT}"
        "-DFUZZ_ARTIFACT_DIRECTORY=${FUZZ_ARTIFACT_DIRECTORY}"
        -P "${FUZZ_RUNNER}"
    RESULT_VARIABLE FUZZ_SAFETY_RESULT)

if(FUZZ_SAFETY_RESULT STREQUAL "0")
    message(FATAL_ERROR "unsafe scratch/protected overlap was accepted")
endif()
if(NOT EXISTS "${FUZZ_SEED_MARKER}")
    message(FATAL_ERROR "unsafe runner removed the protected seed marker")
endif()
