Document: libmustache
Title: Debian libmustache Manual
Author: <insert document author here>
Abstract: This manual describes what libmustache is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libmustache/libmustache.sgml.gz

Format: postscript
Files: /usr/share/doc/libmustache/libmustache.ps.gz

Format: text
Files: /usr/share/doc/libmustache/libmustache.text.gz

Format: HTML
Index: /usr/share/doc/libmustache/html/index.html
Files: /usr/share/doc/libmustache/html/*.html
