name: ci

on:
  push:
    branches:
      - master
      - github-actions
      - ci
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        cpp-version: [gcc, clang]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: sudo apt-get install -y ${{ matrix.cfg.cpp-version }} -y autoconf automake libtool m4 make pkg-config libjson-c-dev libyaml-dev
      - run: autoreconf -fiv
      - run: ./configure
      - run: make
      - run: make check
      - run: make distcheck
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.05
    - run: nix-build
    - run: nix-build nix/ci.nix
