name: linux

on:
  push:
    branches:
      - master
      - github-actions
      - ci
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        cpp-version: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@master
      - run: sudo apt-get install -y ${{ matrix.cfg.cpp-version }} -y autoconf automake libtool m4 make pkg-config libjson-c-dev libyaml-dev
      - run: autoreconf -fiv
      - run: ./configure
      - run: make
      - run: make check
      - run: make distcheck
